#!/bin/bash
CGO_ENABLED=1 \
  GOOS=windows \
  GOARCH=amd64 \
  CC=x86_64-w64-mingw32-gcc \
  CXX=x86_64-w64-mingw32-g++ \
  go build -v \
  -o dist/astrology.exe \
  -ldflags "-extldflags '-static -fpic -Wl,--allow-multiple-definition'" \
  .
