#!/bin/bash

# --- Set the C Cross-Compiler for 64-bit Windows ---
# This assumes you have installed the 'mingw-w64' package.
export CC="x86_64-w64-mingw32-gcc"

# Now run the fyne package command
# Use the -name flag to set the output executable file name to 'astrology'
fyne package \
  -os linux \
  -release \
  -id astrology.rickroll \
  -icon Icon.png \
  -name astrology \
  ./release
